# Generated by Django 2.2.4 on 2020-01-28 18:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20200125_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
