# Generated by Django 2.2.4 on 2020-01-31 08:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cart_cart_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='cart_uuid',
            new_name='public_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='cart_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_item_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_item_updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carts.Cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
