# Generated by Django 2.2.4 on 2020-01-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_tracking_number', models.IntegerField()),
                ('shipment_status', models.IntegerField()),
                ('shipment_type', models.CharField(max_length=50)),
                ('shipment_date', models.DateField(blank=True, null=True)),
                ('destination_city', models.CharField(max_length=50)),
                ('destination_zip_code', models.IntegerField()),
                ('destination_adress_street', models.CharField(max_length=300)),
                ('destination_adress_building', models.CharField(max_length=5)),
                ('destination_other_details', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
