# Generated by Django 2.2.4 on 2020-01-26 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200125_0926'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_tracking_number', models.IntegerField()),
                ('shipment_status', models.IntegerField()),
                ('shipment_type', models.CharField(max_length=50)),
                ('shipment_date', models.DateField(blank=True, null=True)),
                ('destination_city', models.CharField(max_length=50)),
                ('destination_zip_code', models.IntegerField()),
                ('destination_adress_street', models.CharField(max_length=300)),
                ('destination_adress_building', models.CharField(max_length=5)),
                ('destination_other_details', models.CharField(blank=True, max_length=500)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.Order')),
            ],
        ),
        migrations.DeleteModel(
            name='Shipments',
        ),
    ]
