# Generated by Django 2.2.4 on 2020-01-30 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_auto_20200126_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_status',
            field=models.IntegerField(choices=[(1, 'Packing'), (2, 'Picked up by courier'), (3, 'In transit'), (4, 'Delivered')], default=1),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_type',
            field=models.CharField(choices=[('HOME', 'Home delivery'), ('DROP', 'Drop point'), ('PICKUP', 'Pick up at store')], default='HOME', max_length=50),
        ),
    ]
