# Generated by Django 2.2.4 on 2020-02-22 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_auto_20200131_0807'),
        ('shipments', '0003_auto_20200130_1024'),
    ]

    operations = [
    ]
