# Generated by Django 2.2.4 on 2020-02-11 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_merge_20200203_1102'),
        ('shipments', '0004_merge_20200204_0738'),
    ]

    operations = [
    ]
