# Generated by Django 2.2.4 on 2020-02-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_auto_20200202_1107'),
        ('shipments', '0004_merge_20200203_1102'),
    ]

    operations = [
    ]
