# Generated by Django 2.2.4 on 2020-02-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_auto_20200211_2025'),
        ('shipments', '0004_merge_20200204_0738'),
        ('shipments', '0004_merge_20200218_1033'),
    ]

    operations = [
    ]
