# Generated by Django 2.2.4 on 2020-03-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0009_merge_20200226_1000'),
        ('shipments', '0009_merge_20200224_1358'),
        ('shipments', '0004_merge_20200222_2011'),
        ('shipments', '0009_merge_20200224_1737'),
    ]

    operations = [
    ]
