# Generated by Django 2.2.4 on 2020-03-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0009_merge_20200223_1629'),
        ('shipments', '0010_merge_20200302_1150'),
    ]

    operations = [
    ]
