# Generated by Django 2.2.4 on 2020-03-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0011_merge_20200304_1853'),
        ('shipments', '0010_merge_20200303_1902'),
    ]

    operations = [
    ]
