# Generated by Django 2.2.4 on 2020-02-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_how', models.CharField(choices=[('one', 'SMS'), ('two', 'Viber'), ('three', 'Mail'), ('four', 'Telegram')], default='three', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='notificator',
            name='notification_how',
        ),
    ]
