# Generated by Django 2.2.4 on 2020-02-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20200213_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificator',
            name='notification_how',
            field=models.CharField(choices=[('one', 'SMS'), ('two', 'Viber'), ('three', 'Mail'), ('four', 'Telegram')], default='three', max_length=1),
        ),
    ]
