# Generated by Django 2.2.4 on 2020-02-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificator_notification_how'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
