# Generated by Django 2.2.4 on 2020-02-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_delete_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificator',
            name='notification_title',
            field=models.CharField(default='Hello', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificator',
            name='notification_how',
            field=models.CharField(choices=[('one', 'SMS'), ('two', 'Viber'), ('three', 'Mail'), ('four', 'Telegram')], default='three', max_length=20),
        ),
    ]
