# Generated by Django 2.2.4 on 2020-01-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200127_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='user',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='userphone',
            old_name='user',
            new_name='user_profile',
        ),
    ]
