# Generated by Django 2.2.4 on 2020-01-30 10:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200130_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='uu_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='userphone',
            name='uu_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uu_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
