# Generated by Django 2.2.4 on 2020-03-19 14:07

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200130_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.user_avatar_path),
        ),
    ]
