# Generated by Django 2.2.4 on 2020-03-04 17:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20200220_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='logstransaction',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
