# Generated by Django 2.2.4 on 2020-03-14 12:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_logstransaction_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[['new', 'new'], ['in process', 'in process'], ['ready', 'ready']], max_length=100, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Payment')),
            ],
        ),
        migrations.DeleteModel(
            name='LogsTransaction',
        ),
    ]
