# Generated by Django 2.2.4 on 2020-03-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20200314_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('in process', 'in process'), ('ready', 'ready')], default='new', max_length=100, null=True),
        ),
    ]
