# Generated by Django 2.2.4 on 2020-01-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gtin',
            field=models.CharField(help_text='GTIN: Global Trade Item Number', max_length=14),
        ),
        migrations.AlterField(
            model_name='product',
            name='scu',
            field=models.CharField(help_text='SCU: Stock Keeping Unit', max_length=32),
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField(default=0)),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
