# Generated by Django 2.2.4 on 2020-01-27 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200125_2253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Set',
            new_name='Kit',
        ),
    ]
