# Generated by Django 2.2.4 on 2020-01-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200127_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='price',
        ),
        migrations.AddField(
            model_name='kit',
            name='discount',
            field=models.PositiveIntegerField(default=0, help_text='%%: Percentage discount'),
        ),
    ]
