# Generated by Django 2.2.4 on 2020-01-24 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(verbose_name='time ordered')),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('completed', 'completed'), ('rejected', 'rejected')], default='accepted', max_length=20)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.UserProfile')),
            ],
        ),
    ]
