# Generated by Django 2.2.4 on 2020-01-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
