# Generated by Django 2.2.4 on 2020-01-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
    ]
