# Generated by Django 2.2.4 on 2020-01-24 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_time',
        ),
        migrations.AddField(
            model_name='order',
            name='accepting_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Accepting time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='completing_or_rejecting_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Completing or rejecting time'),
            preserve_default=False,
        ),
    ]
