# Generated by Django 2.2.4 on 2020-01-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200124_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='completing_or_rejecting_time',
            field=models.DateTimeField(blank=True, verbose_name='Completing or rejecting time'),
        ),
    ]
