# Generated by Django 2.2.4 on 2020-01-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200124_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completing_or_rejecting_time',
            field=models.DateTimeField(null=True, verbose_name='Completing or rejecting time'),
        ),
    ]
