# Generated by Django 2.2.4 on 2020-01-26 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200125_0926'),
    ]

    operations = [
        #migrations.AlterField(
        #    model_name='order',
        #    name='user_profile',
        #    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.UserProfile'),
        #),
    ]
