# Generated by Django 2.2.4 on 2020-01-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200126_1707'),
        ('orders', '0013_auto_20200126_1134'),
    ]

    operations = [
    ]
