# Generated by Django 2.2.4 on 2020-02-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_merge_20200129_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_uuid',
            new_name='pub_id',
        ),
    ]
