# Generated by Django 2.2.4 on 2020-02-01 11:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200201_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='pub_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
