# Generated by Django 2.2.10 on 2020-02-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderitem_pub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('completed', 'completed'), ('rejected', 'rejected'), ('cancelled', 'cancelled')], default='accepted', max_length=20),
        ),
    ]
